-- AlterTable
ALTER TABLE "Location" ADD COLUMN "mapX" DOUBLE PRECISION,
ADD COLUMN "mapY" DOUBLE PRECISION,
ADD COLUMN "mapZoom" INTEGER,
ADD COLUMN "iconType" TEXT NOT NULL DEFAULT 'emoji',
ADD COLUMN "iconData" TEXT;
